CREATE TABLE alumnos (

	id				INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nombre			VARCHAR(255) NOT NULL,
	email 			VARCHAR(255) NOT NULL,
	password		VARCHAR(255) NOT NULL

)DEFAULT CHARACTER SET UTF8 ENGINE=InnoDB;

CREATE TABLE archivos (

	id				INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	id_alumno		INT,
	titulo 			VARCHAR(255) NOT NULL,
	create_at		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	
	FOREIGN KEY (id_alumno) REFERENCES alumnos(id)
			ON UPDATE  CASCADE
			ON DELETE  SET NULL

)DEFAULT CHARACTER SET UTF8 ENGINE=InnoDB;